name: Build

on: 
  push:
    branches:
      - master

env:
  CGO_ENABLED: 0
  GO111MODULE: on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux,windows,darwin]
        arch: [amd64]
    env:
      GOOS: ${{ matrix.os}}
      GOARCH: ${{ matrix.arch }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        id: build-binary
        run: |
          if [ $GOOS = "windows" ]
          then
            EXT=".exe"
          fi
          go build -trimpath -v -o ./bin/blc-${{env.GOOS}}-${{env.GOARCH}}$EXT
          echo "::set-output name=filename::blc-${{env.GOOS}}-${{env.GOARCH}}$EXT"
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: blc-${{env.GOOS}}-${{env.GOARCH}}
          path: ./bin/${{ steps.build-binary.outputs.filename }}
          if-no-files-found: error
